####**NUMPY**

numpy is a python library for fast numerical numerical computing . it provides support for n dimensional arrays

LIST VS NUMPY :   
1. LIST MEI SPEED OF NUMERICAL OPERATIONS IS SLOWER
2. LIST CAN CONTAIN DIFFERENT DATATYPES
3. LESS CONVIENENT AS DIMENSION OF ARRAY INCREASES
4. LIST HAS MORE MEMORY USAGE
5. NUMPY LETS YOU PERFORM THE OPERATION DIRECTLY ON WHOLE ARRAY . THIS IS CALLED **VECTORISATION** LIST MEI TOH MANUALLY LOOP KARNA PADEGA

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
# create an array using numpy
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
# shape of array
print(arr.shape) # (5,) This means 5 elements in one dimension

(5,)


reshape changes the dimension but the total number of elements remain same

In [5]:
#reshape
arr.reshape(1,5) # 2d banadiya

array([[1, 2, 3, 4, 5]])

In [6]:
# 2d array create
arr2 = np.array([
    [1,2,3,4],
    [4,5,6,7],
    [7,8,9,10]
])
print(arr2.shape) #3X4

(3, 4)


In [8]:
#np.arange(start,stop,step)
arr3 = np.arange(0,10,2) # stop is not include
print(arr3)

[0 2 4 6 8]


In [9]:
arr4 = np.arange(5) # this is considered as stop and start is assumed 0
print(arr4)

[0 1 2 3 4]


In [11]:
arr5 = np.ones((3,4)) # array of 3*4 with all ones
# ek extra bracket
print(arr5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
arr6 = np.eye(3) # identity matrix od 3*3 only diag ele are 1
print(arr6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)#(2,3)
print(arr.ndim)#2 as 2d
print(arr.size) #6
print(arr.dtype)#int64
print(arr.itemsize)#8

(2, 3)
2
6
int64
8


In [15]:
#numpy vectorised operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#element wise addition
print(arr1 + arr2)

[11 22 33 44 55]


In [16]:
numbers = [1, 2, 3, 4, 5]

result = []

for x in numbers:
    result.append(x * 2)

print(result)

[2, 4, 6, 8, 10]


In [17]:
numbers = np.array([1, 2, 3, 4, 5])

result = numbers * 2

print(result)

[ 2  4  6  8 10]


In [18]:
#universal function : a function that can work on evey element of a numpy array automatically

arr = np.array([1,4,9,16])
print(np.sqrt(arr))#like vectorisation

print(np.exp(arr)) #e^x

print(np.sin(arr))


[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]


In [20]:
#NumPy Indexing and Slicing

arr = np.array([10,20,30,40,50])

print(arr[0]) #0 based indexing

#negative indexing
print(arr[-1])#50


#slicing : getting multiple elements from array
#arr[start:stop:step]


10
50


In [21]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

#indexing
print(a[1, 1])

#slicing
print(a[:2 , :2]) # pehle konsi row , phir konsi col

50
[[10 20]
 [40 50]]


In [22]:
#modify elements
a = np.array([10, 20, 30, 40, 50])

a[2] = 100
print(a)

a[1:4] = 99
print(a)

a[1:4] = [200, 300, 400]
print(a)

[ 10  20 100  40  50]
[10 99 99 99 50]
[ 10 200 300 400  50]


In [23]:
#normalisation : mean of 0 and std dev as 1

data = np.array([1,2,3,4,5])
mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean) / std_dev

print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [24]:
data = np.arange(0,11)

#mean
mean = np.mean(data)
print(mean)

#median
median = np.median(data)
print(median)

#std dev
std_dev = np.std(data)
print(std_dev)

#variance
variance = np.var(data)
print(variance)

5.0
5.0
3.1622776601683795
10.0


In [25]:
# logical operations

a = np.array([10, 20, 30, 40, 50])
print(a>30)

[False False False  True  True]


In [26]:
# filtering

print(a[a>30])

[40 50]


ADVANCED CONCEPTS IN NUMPY


In [27]:
# axis in numpy : it tells in which direction to perform operation

a = np.array([
    [1,2,3],
    [4,5,6]
])
#axis = 0 -> column wise

print(np.sum(a))
print(np.sum(a,axis=0)) #[5,7,9]

21
[5 7 9]


In [30]:
#aggregate function : reducing many values into a single value
a = np.array([1,2,3,4,5])

print(np.sum(a))
print(np.mean(a))

15
3.0


In [31]:
# sort
a = np.array([1,2,5,6,3,2])
print(np.sort(a)) # sorted
print(a) # not changes original

a.sort()
print(a) # changes original

[1 2 2 3 5 6]
[1 2 5 6 3 2]
[1 2 2 3 5 6]


In [32]:
# concatenating
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))

print(c) #[1 2 3 4 5 6]

[1 2 3 4 5 6]


In [33]:
# stacking
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#vertical stacking
print(np.vstack((a, b)))
#horizontal stacking
print(np.hstack((a, b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [34]:
#copy vs view

a = np.array([1, 2, 3, 4])

b = a.view()

b[0] = 100

print(a) #[100 2 3 4] # changing b also changed a


a = np.array([1, 2, 3, 4])

b = a.copy()

b[0] = 100

print(a) # [1,2,3,4]

[100   2   3   4]
[1 2 3 4]


In [38]:
x =np.random.randint(1,10) # this generates a random integer from 1 to 9
print(x)

y = np.random.randint(1,10,5) # 5 numbers
print(y)

5
[6 2 3 1 1]


In [39]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

# element wise multiplication
print(A*B)

#matrix multiplication
print(A@B)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [41]:
# linear algebra
A = np.array([
    [1, 2],
    [3, 4]
])
print(np.linalg.det(A))       # determinant
print(np.linalg.inv(A))       # inverse
print(np.linalg.eig(A))       # eigenvalues/eigenvectors

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [43]:
# broadcasting

# array + single number
a = np.array([1,2,3])
print(a+10)

#[1  2  3]
#[10 10 10]
#---------
#[11 12 13]

[11 12 13]


In [44]:
#2d array + 1darray
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([10, 20, 30])

print(a+b)

[[11 22 33]
 [14 25 36]]


In [45]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([
    [10],
    [20]
])

print(a + b)

[[11 12 13]
 [24 25 26]]
